version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados
    networks:
      - mynetwork
    ports:
      - "5432:5432"  # Expondo a porta do PostgreSQL

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"  # Expondo a porta do pgAdmin
    networks:
      - mynetwork
    depends_on:
      - db  # Garantir que o pgAdmin só suba após o PostgreSQL

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
