name: Build and Deploy

on:
  push:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: nome_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -h localhost" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r Backend/requirements.txt

      - name: Wait for PostgreSQL
        run: |
          for i in {1..20}; do
            PGPASSWORD=admin psql -h localhost -U postgres -d nome_database -c "SELECT 1" && echo "PostgreSQL está pronto!" && break
            echo "Esperando pelo PostgreSQL..."
            sleep 5
          done

      - name: Check PostgreSQL status
        run: PGPASSWORD=admin psql -h localhost -U postgres -d nome_database -c "SELECT 1"

      - name: Run pytest
        env:
          DATABASE_URL: postgresql://postgres:admin@localhost:5432/nome_database
        run: pytest PDSI_2_Prototipo/Backend/teste.py
