name: Build and Deploy
on:
  push:
  pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: nome_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -h localhost" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2

      - name: instalando o python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: instalar dependencias
        run: pip install -r Backend/requirements.txt

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Check PostgreSQL status
        run: pg_isready -h localhost -p 5432

      - name: Executar pytest
        env:
          DATABASE_URL: postgresql://postgres:admin@localhost:5432/nome_database
        run: pytest Backend/teste.py
